server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: gd-platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/gd_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      # password: ${REDIS_PASSWORD:}  # 生产环境必填
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  mail:
    host: smtp.qq.com
    port: 587
    username: gd_platform@foxmail.com
    password: nltoannfuvybcgjj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

gd:
  jwt:
    secret: "GdPlatformJwtSecretKey2024MustBe256BitsLongForHS256Algorithm!!"
    expire-minutes: 720
  upload:
    path: ./uploads
